#!/bin/bash

set -e

get_loadavg() {
  echo " "$(cut -f 1-3 -d ' ' /proc/loadavg)" "
}

get_freem() {
  echo " "$(free -m | awk 'NR==2 { print $7 }')" MB "
}

get_date() {
  echo " "$(date '+%Y %b %d (%a) %I:%M:%S %p')" "
}

while :; do
  xsetroot -name "$(get_loadavg) $(get_freem) $(get_date)"

  sleep 1s
done
